import { PokemonSummary, PokemonType } from "./schemas";
import { getArtworkUrl, getShowdownUrl, getThumbnailUrl } from "./seed";

export interface Gen1PokemonEntry {
  id: number;
  name: string;
  types: PokemonType[];
  baseExperience: number;
}

export const GEN1_RAW_LIST: Gen1PokemonEntry[] = [
  { id: 1, name: "bulbasaur", types: ["grass", "poison"], baseExperience: 64 },
  { id: 2, name: "ivysaur", types: ["grass", "poison"], baseExperience: 142 },
  { id: 3, name: "venusaur", types: ["grass", "poison"], baseExperience: 236 },
  { id: 4, name: "charmander", types: ["fire"], baseExperience: 62 },
  { id: 5, name: "charmeleon", types: ["fire"], baseExperience: 142 },
  { id: 6, name: "charizard", types: ["fire", "flying"], baseExperience: 240 },
  { id: 7, name: "squirtle", types: ["water"], baseExperience: 63 },
  { id: 8, name: "wartortle", types: ["water"], baseExperience: 142 },
  { id: 9, name: "blastoise", types: ["water"], baseExperience: 239 },
  { id: 10, name: "caterpie", types: ["bug"], baseExperience: 39 },
  { id: 11, name: "metapod", types: ["bug"], baseExperience: 72 },
  { id: 12, name: "butterfree", types: ["bug", "flying"], baseExperience: 178 },
  { id: 13, name: "weedle", types: ["bug", "poison"], baseExperience: 39 },
  { id: 14, name: "kakuna", types: ["bug", "poison"], baseExperience: 72 },
  { id: 15, name: "beedrill", types: ["bug", "poison"], baseExperience: 178 },
  { id: 16, name: "pidgey", types: ["normal", "flying"], baseExperience: 50 },
  { id: 17, name: "pidgeotto", types: ["normal", "flying"], baseExperience: 122 },
  { id: 18, name: "pidgeot", types: ["normal", "flying"], baseExperience: 216 },
  { id: 19, name: "rattata", types: ["normal"], baseExperience: 51 },
  { id: 20, name: "raticate", types: ["normal"], baseExperience: 145 },
  { id: 21, name: "spearow", types: ["normal", "flying"], baseExperience: 52 },
  { id: 22, name: "fearow", types: ["normal", "flying"], baseExperience: 155 },
  { id: 23, name: "ekans", types: ["poison"], baseExperience: 58 },
  { id: 24, name: "arbok", types: ["poison"], baseExperience: 157 },
  { id: 25, name: "pikachu", types: ["electric"], baseExperience: 112 },
  { id: 26, name: "raichu", types: ["electric"], baseExperience: 218 },
  { id: 27, name: "sandshrew", types: ["ground"], baseExperience: 60 },
  { id: 28, name: "sandslash", types: ["ground"], baseExperience: 158 },
  { id: 29, name: "nidoran-f", types: ["poison"], baseExperience: 55 },
  { id: 30, name: "nidorina", types: ["poison"], baseExperience: 128 },
  { id: 31, name: "nidoqueen", types: ["poison", "ground"], baseExperience: 227 },
  { id: 32, name: "nidoran-m", types: ["poison"], baseExperience: 55 },
  { id: 33, name: "nidorino", types: ["poison"], baseExperience: 128 },
  { id: 34, name: "nidoking", types: ["poison", "ground"], baseExperience: 227 },
  { id: 35, name: "clefairy", types: ["fairy"], baseExperience: 113 },
  { id: 36, name: "clefable", types: ["fairy"], baseExperience: 217 },
  { id: 37, name: "vulpix", types: ["fire"], baseExperience: 60 },
  { id: 38, name: "ninetales", types: ["fire"], baseExperience: 177 },
  { id: 39, name: "jigglypuff", types: ["normal", "fairy"], baseExperience: 95 },
  { id: 40, name: "wigglytuff", types: ["normal", "fairy"], baseExperience: 196 },
  { id: 41, name: "zubat", types: ["poison", "flying"], baseExperience: 49 },
  { id: 42, name: "golbat", types: ["poison", "flying"], baseExperience: 159 },
  { id: 43, name: "oddish", types: ["grass", "poison"], baseExperience: 64 },
  { id: 44, name: "gloom", types: ["grass", "poison"], baseExperience: 138 },
  { id: 45, name: "vileplume", types: ["grass", "poison"], baseExperience: 221 },
  { id: 46, name: "paras", types: ["bug", "grass"], baseExperience: 57 },
  { id: 47, name: "parasect", types: ["bug", "grass"], baseExperience: 142 },
  { id: 48, name: "venonat", types: ["bug", "poison"], baseExperience: 61 },
  { id: 49, name: "venomoth", types: ["bug", "poison"], baseExperience: 158 },
  { id: 50, name: "diglett", types: ["ground"], baseExperience: 53 },
  { id: 51, name: "dugtrio", types: ["ground"], baseExperience: 149 },
  { id: 52, name: "meowth", types: ["normal"], baseExperience: 58 },
  { id: 53, name: "persian", types: ["normal"], baseExperience: 154 },
  { id: 54, name: "psyduck", types: ["water"], baseExperience: 64 },
  { id: 55, name: "golduck", types: ["water"], baseExperience: 175 },
  { id: 56, name: "mankey", types: ["fighting"], baseExperience: 61 },
  { id: 57, name: "primeape", types: ["fighting"], baseExperience: 159 },
  { id: 58, name: "growlithe", types: ["fire"], baseExperience: 70 },
  { id: 59, name: "arcanine", types: ["fire"], baseExperience: 194 },
  { id: 60, name: "poliwag", types: ["water"], baseExperience: 60 },
  { id: 61, name: "poliwhirl", types: ["water"], baseExperience: 135 },
  { id: 62, name: "poliwrath", types: ["water", "fighting"], baseExperience: 230 },
  { id: 63, name: "abra", types: ["psychic"], baseExperience: 62 },
  { id: 64, name: "kadabra", types: ["psychic"], baseExperience: 140 },
  { id: 65, name: "alakazam", types: ["psychic"], baseExperience: 225 },
  { id: 66, name: "machop", types: ["fighting"], baseExperience: 61 },
  { id: 67, name: "machoke", types: ["fighting"], baseExperience: 142 },
  { id: 68, name: "machamp", types: ["fighting"], baseExperience: 227 },
  { id: 69, name: "bellsprout", types: ["grass", "poison"], baseExperience: 60 },
  { id: 70, name: "weepinbell", types: ["grass", "poison"], baseExperience: 137 },
  { id: 71, name: "victreebel", types: ["grass", "poison"], baseExperience: 221 },
  { id: 72, name: "tentacool", types: ["water", "poison"], baseExperience: 67 },
  { id: 73, name: "tentacruel", types: ["water", "poison"], baseExperience: 182 },
  { id: 74, name: "geodude", types: ["rock", "ground"], baseExperience: 60 },
  { id: 75, name: "graveler", types: ["rock", "ground"], baseExperience: 137 },
  { id: 76, name: "golem", types: ["rock", "ground"], baseExperience: 223 },
  { id: 77, name: "ponyta", types: ["fire"], baseExperience: 82 },
  { id: 78, name: "rapidash", types: ["fire"], baseExperience: 175 },
  { id: 79, name: "slowpoke", types: ["water", "psychic"], baseExperience: 63 },
  { id: 80, name: "slowbro", types: ["water", "psychic"], baseExperience: 172 },
  { id: 81, name: "magnemite", types: ["electric", "steel"], baseExperience: 65 },
  { id: 82, name: "magneton", types: ["electric", "steel"], baseExperience: 163 },
  { id: 83, name: "farfetchd", types: ["normal", "flying"], baseExperience: 132 },
  { id: 84, name: "doduo", types: ["normal", "flying"], baseExperience: 62 },
  { id: 85, name: "dodrio", types: ["normal", "flying"], baseExperience: 165 },
  { id: 86, name: "seel", types: ["water"], baseExperience: 65 },
  { id: 87, name: "dewgong", types: ["water", "ice"], baseExperience: 166 },
  { id: 88, name: "grimer", types: ["poison"], baseExperience: 65 },
  { id: 89, name: "muk", types: ["poison"], baseExperience: 175 },
  { id: 90, name: "shellder", types: ["water"], baseExperience: 61 },
  { id: 91, name: "cloyster", types: ["water", "ice"], baseExperience: 184 },
  { id: 92, name: "gastly", types: ["ghost", "poison"], baseExperience: 62 },
  { id: 93, name: "haunter", types: ["ghost", "poison"], baseExperience: 142 },
  { id: 94, name: "gengar", types: ["ghost", "poison"], baseExperience: 225 },
  { id: 95, name: "onix", types: ["rock", "ground"], baseExperience: 77 },
  { id: 96, name: "drowzee", types: ["psychic"], baseExperience: 66 },
  { id: 97, name: "hypno", types: ["psychic"], baseExperience: 169 },
  { id: 98, name: "krabby", types: ["water"], baseExperience: 65 },
  { id: 99, name: "kingler", types: ["water"], baseExperience: 166 },
  { id: 100, name: "voltorb", types: ["electric"], baseExperience: 66 },
  { id: 101, name: "electrode", types: ["electric"], baseExperience: 172 },
  { id: 102, name: "exeggcute", types: ["grass", "psychic"], baseExperience: 65 },
  { id: 103, name: "exeggutor", types: ["grass", "psychic"], baseExperience: 186 },
  { id: 104, name: "cubone", types: ["ground"], baseExperience: 64 },
  { id: 105, name: "marowak", types: ["ground"], baseExperience: 149 },
  { id: 106, name: "hitmonlee", types: ["fighting"], baseExperience: 159 },
  { id: 107, name: "hitmonchan", types: ["fighting"], baseExperience: 159 },
  { id: 108, name: "lickitung", types: ["normal"], baseExperience: 77 },
  { id: 109, name: "koffing", types: ["poison"], baseExperience: 68 },
  { id: 110, name: "weezing", types: ["poison"], baseExperience: 172 },
  { id: 111, name: "rhyhorn", types: ["ground", "rock"], baseExperience: 69 },
  { id: 112, name: "rhydon", types: ["ground", "rock"], baseExperience: 170 },
  { id: 113, name: "chansey", types: ["normal"], baseExperience: 395 },
  { id: 114, name: "tangela", types: ["grass"], baseExperience: 87 },
  { id: 115, name: "kangaskhan", types: ["normal"], baseExperience: 172 },
  { id: 116, name: "horsea", types: ["water"], baseExperience: 59 },
  { id: 117, name: "seadra", types: ["water"], baseExperience: 154 },
  { id: 118, name: "goldeen", types: ["water"], baseExperience: 64 },
  { id: 119, name: "seaking", types: ["water"], baseExperience: 158 },
  { id: 120, name: "staryu", types: ["water"], baseExperience: 68 },
  { id: 121, name: "starmie", types: ["water", "psychic"], baseExperience: 182 },
  { id: 122, name: "mr-mime", types: ["psychic", "fairy"], baseExperience: 161 },
  { id: 123, name: "scyther", types: ["bug", "flying"], baseExperience: 100 },
  { id: 124, name: "jynx", types: ["ice", "psychic"], baseExperience: 159 },
  { id: 125, name: "electabuzz", types: ["electric"], baseExperience: 172 },
  { id: 126, name: "magmar", types: ["fire"], baseExperience: 173 },
  { id: 127, name: "pinsir", types: ["bug"], baseExperience: 175 },
  { id: 128, name: "tauros", types: ["normal"], baseExperience: 172 },
  { id: 129, name: "magikarp", types: ["water"], baseExperience: 40 },
  { id: 130, name: "gyarados", types: ["water", "flying"], baseExperience: 189 },
  { id: 131, name: "lapras", types: ["water", "ice"], baseExperience: 187 },
  { id: 132, name: "ditto", types: ["normal"], baseExperience: 101 },
  { id: 133, name: "eevee", types: ["normal"], baseExperience: 65 },
  { id: 134, name: "vaporeon", types: ["water"], baseExperience: 184 },
  { id: 135, name: "jolteon", types: ["electric"], baseExperience: 184 },
  { id: 136, name: "flareon", types: ["fire"], baseExperience: 184 },
  { id: 137, name: "porygon", types: ["normal"], baseExperience: 79 },
  { id: 138, name: "omanyte", types: ["rock", "water"], baseExperience: 71 },
  { id: 139, name: "omastar", types: ["rock", "water"], baseExperience: 173 },
  { id: 140, name: "kabuto", types: ["rock", "water"], baseExperience: 71 },
  { id: 141, name: "kabutops", types: ["rock", "water"], baseExperience: 173 },
  { id: 142, name: "aerodactyl", types: ["rock", "flying"], baseExperience: 180 },
  { id: 143, name: "snorlax", types: ["normal"], baseExperience: 189 },
  { id: 144, name: "articuno", types: ["ice", "flying"], baseExperience: 261 },
  { id: 145, name: "zapdos", types: ["electric", "flying"], baseExperience: 261 },
  { id: 146, name: "moltres", types: ["fire", "flying"], baseExperience: 261 },
  { id: 147, name: "dratini", types: ["dragon"], baseExperience: 60 },
  { id: 148, name: "dragonair", types: ["dragon"], baseExperience: 147 },
  { id: 149, name: "dragonite", types: ["dragon", "flying"], baseExperience: 270 },
  { id: 150, name: "mewtwo", types: ["psychic"], baseExperience: 306 },
  { id: 151, name: "mew", types: ["psychic"], baseExperience: 270 },
];

export const ALL_GEN1_SUMMARY_LIST: PokemonSummary[] = GEN1_RAW_LIST.map((p) => ({
  id: p.id,
  name: p.name,
  types: p.types,
  sprites: {
    thumbnail: getThumbnailUrl(p.id),
    artwork: getArtworkUrl(p.id),
    showdownFront: getShowdownUrl(p.id),
    showdownBack: getShowdownUrl(p.id, true),
  },
  baseExperience: p.baseExperience,
}));
