import { PokemonDetail, PokemonSummary } from "./schemas";

export const getArtworkUrl = (id: number): string =>
  `https://cdn.jsdelivr.net/gh/PokeAPI/sprites@master/sprites/pokemon/other/official-artwork/${id}.png`;

export const getThumbnailUrl = (id: number): string =>
  `https://cdn.jsdelivr.net/gh/PokeAPI/sprites@master/sprites/pokemon/${id}.png`;

export const getShowdownUrl = (id: number, back = false): string =>
  `https://cdn.jsdelivr.net/gh/PokeAPI/sprites@master/sprites/pokemon/other/showdown/${back ? "back/" : ""}${id}.gif`;

export const SEED_POKEMON_LIST: PokemonDetail[] = [
  {
    id: 1,
    name: "bulbasaur",
    types: ["grass", "poison"],
    baseExperience: 64,
    height: 7,
    weight: 69,
    sprites: {
      thumbnail: getThumbnailUrl(1),
      artwork: getArtworkUrl(1),
      showdownFront: getShowdownUrl(1),
      showdownBack: getShowdownUrl(1, true),
    },
    stats: { hp: 45, attack: 49, defense: 49, specialAttack: 65, specialDefense: 65, speed: 45 },
    abilities: ["Overgrow", "Chlorophyll"],
    species: {
      genus: "Seed Pokémon",
      flavorText: "A strange seed was planted on its back at birth. The plant sprouts and grows with this Pokémon.",
      color: "green",
      evolutionChainId: 1,
    },
    moves: [
      { id: 22, name: "vine-whip", type: "grass", power: 45, accuracy: 100, pp: 25, priority: 0, damageClass: "physical" },
      { id: 73, name: "leech-seed", type: "grass", power: null, accuracy: 90, pp: 10, priority: 0, damageClass: "status" },
      { id: 75, name: "razor-leaf", type: "grass", power: 55, accuracy: 95, pp: 25, priority: 0, damageClass: "physical" },
      { id: 77, name: "poison-powder", type: "poison", power: null, accuracy: 75, pp: 35, priority: 0, damageClass: "status" },
    ],
  },
  {
    id: 4,
    name: "charmander",
    types: ["fire"],
    baseExperience: 62,
    height: 6,
    weight: 85,
    sprites: {
      thumbnail: getThumbnailUrl(4),
      artwork: getArtworkUrl(4),
      showdownFront: getShowdownUrl(4),
      showdownBack: getShowdownUrl(4, true),
    },
    stats: { hp: 39, attack: 52, defense: 43, specialAttack: 60, specialDefense: 50, speed: 65 },
    abilities: ["Blaze", "Solar Power"],
    species: {
      genus: "Lizard Pokémon",
      flavorText: "The flame on its tail indicates Charmander's life force. If it is healthy, the flame burns brightly.",
      color: "red",
      evolutionChainId: 2,
    },
    moves: [
      { id: 10, name: "scratch", type: "normal", power: 40, accuracy: 100, pp: 35, priority: 0, damageClass: "physical" },
      { id: 52, name: "ember", type: "fire", power: 40, accuracy: 100, pp: 25, priority: 0, damageClass: "special" },
      { id: 53, name: "flamethrower", type: "fire", power: 90, accuracy: 100, pp: 15, priority: 0, damageClass: "special" },
      { id: 82, name: "dragon-rage", type: "dragon", power: 40, accuracy: 100, pp: 10, priority: 0, damageClass: "special" },
    ],
  },
  {
    id: 7,
    name: "squirtle",
    types: ["water"],
    baseExperience: 63,
    height: 5,
    weight: 90,
    sprites: {
      thumbnail: getThumbnailUrl(7),
      artwork: getArtworkUrl(7),
      showdownFront: getShowdownUrl(7),
      showdownBack: getShowdownUrl(7, true),
    },
    stats: { hp: 44, attack: 48, defense: 65, specialAttack: 50, specialDefense: 64, speed: 43 },
    abilities: ["Torrent", "Rain Dish"],
    species: {
      genus: "Tiny Turtle Pokémon",
      flavorText: "When it retracts its long neck into its shell, it squirts water with vigorous force.",
      color: "blue",
      evolutionChainId: 3,
    },
    moves: [
      { id: 33, name: "tackle", type: "normal", power: 40, accuracy: 100, pp: 35, priority: 0, damageClass: "physical" },
      { id: 55, name: "water-gun", type: "water", power: 40, accuracy: 100, pp: 25, priority: 0, damageClass: "special" },
      { id: 61, name: "bubble-beam", type: "water", power: 65, accuracy: 100, pp: 20, priority: 0, damageClass: "special" },
      { id: 110, name: "withdraw", type: "water", power: null, accuracy: null, pp: 40, priority: 0, damageClass: "status" },
    ],
  },
  {
    id: 25,
    name: "pikachu",
    types: ["electric"],
    baseExperience: 112,
    height: 4,
    weight: 60,
    sprites: {
      thumbnail: getThumbnailUrl(25),
      artwork: getArtworkUrl(25),
      showdownFront: getShowdownUrl(25),
      showdownBack: getShowdownUrl(25, true),
    },
    stats: { hp: 35, attack: 55, defense: 40, specialAttack: 50, specialDefense: 50, speed: 90 },
    abilities: ["Static", "Lightning Rod"],
    species: {
      genus: "Mouse Pokémon",
      flavorText: "When several of these Pokémon gather, their electricity could build and cause lightning storms.",
      color: "yellow",
      evolutionChainId: 10,
    },
    moves: [
      { id: 84, name: "thunder-shock", type: "electric", power: 40, accuracy: 100, pp: 30, priority: 0, damageClass: "special" },
      { id: 85, name: "thunderbolt", type: "electric", power: 90, accuracy: 100, pp: 15, priority: 0, damageClass: "special" },
      { id: 98, name: "quick-attack", type: "normal", power: 40, accuracy: 100, pp: 30, priority: 1, damageClass: "physical" },
      { id: 86, name: "thunder-wave", type: "electric", power: null, accuracy: 90, pp: 20, priority: 0, damageClass: "status" },
    ],
  },
  {
    id: 94,
    name: "gengar",
    types: ["ghost", "poison"],
    baseExperience: 225,
    height: 15,
    weight: 405,
    sprites: {
      thumbnail: getThumbnailUrl(94),
      artwork: getArtworkUrl(94),
      showdownFront: getShowdownUrl(94),
      showdownBack: getShowdownUrl(94, true),
    },
    stats: { hp: 60, attack: 65, defense: 60, specialAttack: 130, specialDefense: 75, speed: 110 },
    abilities: ["Cursed Body"],
    species: {
      genus: "Shadow Pokémon",
      flavorText: "Should you feel a sudden chill, it is evidence of an approaching Gengar. There is no escaping it.",
      color: "purple",
      evolutionChainId: 40,
    },
    moves: [
      { id: 247, name: "shadow-ball", type: "ghost", power: 80, accuracy: 100, pp: 15, priority: 0, damageClass: "special" },
      { id: 188, name: "sludge-bomb", type: "poison", power: 90, accuracy: 100, pp: 10, priority: 0, damageClass: "special" },
      { id: 95, name: "hypnosis", type: "psychic", power: null, accuracy: 60, pp: 20, priority: 0, damageClass: "status" },
      { id: 138, name: "dream-eater", type: "psychic", power: 100, accuracy: 100, pp: 15, priority: 0, damageClass: "special" },
    ],
  },
  {
    id: 130,
    name: "gyarados",
    types: ["water", "flying"],
    baseExperience: 189,
    height: 65,
    weight: 2350,
    sprites: {
      thumbnail: getThumbnailUrl(130),
      artwork: getArtworkUrl(130),
      showdownFront: getShowdownUrl(130),
      showdownBack: getShowdownUrl(130, true),
    },
    stats: { hp: 95, attack: 125, defense: 79, specialAttack: 60, specialDefense: 100, speed: 81 },
    abilities: ["Intimidate", "Moxie"],
    species: {
      genus: "Atrocious Pokémon",
      flavorText: "Rarely seen in the wild. Huge and vicious, it is capable of destroying entire cities in a rage.",
      color: "blue",
      evolutionChainId: 64,
    },
    moves: [
      { id: 56, name: "hydro-pump", type: "water", power: 110, accuracy: 80, pp: 5, priority: 0, damageClass: "special" },
      { id: 242, name: "crunch", type: "dark", power: 80, accuracy: 100, pp: 15, priority: 0, damageClass: "physical" },
      { id: 89, name: "earthquake", type: "ground", power: 100, accuracy: 100, pp: 10, priority: 0, damageClass: "physical" },
      { id: 53, name: "flamethrower", type: "fire", power: 90, accuracy: 100, pp: 15, priority: 0, damageClass: "special" },
    ],
  },
  {
    id: 143,
    name: "snorlax",
    types: ["normal"],
    baseExperience: 189,
    height: 21,
    weight: 4600,
    sprites: {
      thumbnail: getThumbnailUrl(143),
      artwork: getArtworkUrl(143),
      showdownFront: getShowdownUrl(143),
      showdownBack: getShowdownUrl(143, true),
    },
    stats: { hp: 160, attack: 110, defense: 65, specialAttack: 65, specialDefense: 110, speed: 30 },
    abilities: ["Immunity", "Thick Fat", "Gluttony"],
    species: {
      genus: "Sleeping Pokémon",
      flavorText: "Very lazy. Just eats and sleeps. As its enormous bulk builds, it becomes even more reluctant to move.",
      color: "black",
      evolutionChainId: 72,
    },
    moves: [
      { id: 34, name: "body-slam", type: "normal", power: 85, accuracy: 100, pp: 15, priority: 0, damageClass: "physical" },
      { id: 156, name: "rest", type: "psychic", power: null, accuracy: null, pp: 10, priority: 0, damageClass: "status" },
      { id: 173, name: "snore", type: "normal", power: 50, accuracy: 100, pp: 15, priority: 0, damageClass: "special" },
      { id: 89, name: "earthquake", type: "ground", power: 100, accuracy: 100, pp: 10, priority: 0, damageClass: "physical" },
    ],
  },
  {
    id: 149,
    name: "dragonite",
    types: ["dragon", "flying"],
    baseExperience: 270,
    height: 22,
    weight: 2100,
    sprites: {
      thumbnail: getThumbnailUrl(149),
      artwork: getArtworkUrl(149),
      showdownFront: getShowdownUrl(149),
      showdownBack: getShowdownUrl(149, true),
    },
    stats: { hp: 91, attack: 134, defense: 95, specialAttack: 100, specialDefense: 100, speed: 80 },
    abilities: ["Inner Focus", "Multiscale"],
    species: {
      genus: "Dragon Pokémon",
      flavorText: "An extremely rarely seen marine Pokémon. Its intelligence is said to match that of humans.",
      color: "brown",
      evolutionChainId: 76,
    },
    moves: [
      { id: 337, name: "dragon-claw", type: "dragon", power: 80, accuracy: 100, pp: 15, priority: 0, damageClass: "physical" },
      { id: 407, name: "dragon-rush", type: "dragon", power: 100, accuracy: 75, pp: 10, priority: 0, damageClass: "physical" },
      { id: 58, name: "ice-beam", type: "ice", power: 90, accuracy: 100, pp: 10, priority: 0, damageClass: "special" },
      { id: 87, name: "thunder", type: "electric", power: 110, accuracy: 70, pp: 10, priority: 0, damageClass: "special" },
    ],
  },
  {
    id: 150,
    name: "mewtwo",
    types: ["psychic"],
    baseExperience: 306,
    height: 20,
    weight: 1220,
    sprites: {
      thumbnail: getThumbnailUrl(150),
      artwork: getArtworkUrl(150),
      showdownFront: getShowdownUrl(150),
      showdownBack: getShowdownUrl(150, true),
    },
    stats: { hp: 106, attack: 110, defense: 90, specialAttack: 154, specialDefense: 90, speed: 130 },
    abilities: ["Pressure", "Unnerve"],
    species: {
      genus: "Genetic Pokémon",
      flavorText: "It was created by a scientist after years of horrific gene splicing and DNA engineering experiments.",
      color: "purple",
      evolutionChainId: 77,
    },
    moves: [
      { id: 94, name: "psychic", type: "psychic", power: 90, accuracy: 100, pp: 10, priority: 0, damageClass: "special" },
      { id: 247, name: "shadow-ball", type: "ghost", power: 80, accuracy: 100, pp: 15, priority: 0, damageClass: "special" },
      { id: 105, name: "recover", type: "normal", power: null, accuracy: null, pp: 10, priority: 0, damageClass: "status" },
      { id: 126, name: "fire-blast", type: "fire", power: 110, accuracy: 85, pp: 5, priority: 0, damageClass: "special" },
    ],
  },
];

export const SEED_SUMMARY_LIST: PokemonSummary[] = SEED_POKEMON_LIST.map((p) => ({
  id: p.id,
  name: p.name,
  types: p.types,
  sprites: p.sprites,
  baseExperience: p.baseExperience,
}));
